language: node_js
node_js: 
  - "16"
cache:
  directories:
    - "node_modules"
script:
  - echo '***Build starts***'   
  - echo 'Instaling Dependencies'
  - npm install
  - echo 'Running Tests'
  - npm run test
