language: node_js
node_js: 
  - "16"
cache:
  directories:
    - "node_modules"
install:
  - echo 'Instaling Dependencies'
  - npm install  
script:
  - echo '***Build starts***'   
  - echo 'Running Tests'
  - npm run test
  - echo 'Building'
branches:
  only:
    - master 
# before_script: