language: node_js
node_js: 
  - "16"
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master     
install:
  - echo 'Instaling Dependencies'
  - npm install  
services: 
    - docker  
script:
  - echo '***Build starts***'   
  - echo 'Running Tests'
  - npm run test
  - echo 'Building'
  - docker build -t jennykibiri/freestyle-jenkins-node-app .
  - echo $PASSWORD | docker login  -u $USERNAME --password-stdin 

