version: 2.1
orbs:
  node: circleci/node@4.7
workflows:

  sample: 
    jobs:
      - node/test:
          runs-on: node
          steps:
            - echo '***Installl packages***'
            - npm install
            - echo '***Build starts***'
            - echo 'Running Tests'
            - npm run test
            - echo 'Building'
            - docker build -t jennykibiri/freestyle-jenkins-node-app .
            - echo $PASSWORD | docker login  -u $USERNAME --password-stdin 
            - echo '***Build ends***'
branches:
      only:
      - master      
  


