version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@1.5.0


jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .



  build_docker_image:
    executor: docker
    steps:
      - checkout
      - run:
          command: docker build -t jennykibiri/freestyle-jenkins-node-app .
          name: Build docker image
      - run:
          command: docker push jennykibiri/freestyle-jenkins-node-app
          name: Push docker image 




workflows:
  test_my_app:
    jobs:
      - build_and_test
  build_docker_image:
    jobs:
      - build_docker_image 
   
      

