version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@1.5.0
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: jennykibiri/freestyle-jenkins-node-app
    docker:
      - image: circleci/node:latest
        auth:
            username: $USERNAME
            password: $PASSWORD



jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .



  build_docker_image:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t jennykibiri/freestyle-jenkins-node-app .
      - run:
          name: Publish Docker image
          command: |
            echo "$PASSWORD" | docker login --username "$USERNAME" --password-stdin
            docker push jennykibiri/freestyle-jenkins-node-app
   
  

workflows:
  test_my_app:
    jobs:
      - build_and_test
  build_docker_image:
    jobs:
      - build_docker_image
      

  
   
      

