version: 2.1
orbs:
  node: circleci/node@5.0.2
executors:
  docker-publisher:
    environment:
      IMAGE_TAG: jennykibiri/freestyle-jenkins-node-app:latest
    docker:
      - image: docker:stable


jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .



  build_docker_image:
    executor: docker-publisher
    steps:
      - checkout
      - run:
          name: Build docker image
          command: docker build -t jennykibiri/freestyle-jenkins-node-app .
      - run:
          command: docker push jennykibiri/freestyle-jenkins-node-app
          name: Push docker image 
      - run:
          name: Archive Docker image
          command: docker save --output image.tar "${IMAGE_TAG}"
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
   
  push:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker image
          command: docker load --input /tmp/workspace/image.tar
      - run:
          name: Publish Docker image
          command: |
            echo "${PASSWORD}" | docker login --username "${USERNAME}" --password-stdin
            docker push "${IMAGE_TAG}"



workflows:
  test_my_app:
    jobs:
      - build_and_test
      - build_docker_image
      - push:
          requires:
            - build_and_test
            - build_docker_image
          filters:
            branches:
              only: master  

  
   
      

